
DROP TABLE IF EXISTS aldata;
create table aldata(
	id bigint(20) primary key not null auto_increment,
	cao_id int not null comment "槽号",                 
	cao_ling varchar(20) comment "槽龄(天)",
	cao_xing varchar(10) comment "槽型",
	yunxingshijian int(20) comment "运行时间(分钟)",
	jialiaoliang int(20) comment "加料量(kg)",
	jialiaocishu int(20) comment "加料次数",
	dianyayusheding float(4,3) comment "电压预设定",
	dianyashijisheding float(4,3) comment "电压实际设定",
	gongzuoshidianya float(4,3) comment "工作时电压",
	pingjundianya float(4,3) comment "平均电压",
	dianliu float(5,2) comment "电流",
	zaosheng int comment "噪声(mv)",
	yangjixingchengri int comment "阳极行程日(mm)",
	yangjixingchengdunlv int comment "阳极行程吨铝(mm)",
	dianjiewendu int comment "点解温度",
	fenzibi float(4,3) comment "分子比",
	alfjialiaosheding int comment "ALF加料设定",
	alfjialiaoshiji int comment "ALF加料实际",
	lvshuiping int comment "铝水平",
	dianjiezhishuiping int comment "电解质水平",
	fehanliang float(4,3) comment "Fe含量",
	sihanliang float(4,3) comment "Si含量",
	shijichulvliang int comment "实际出铝量",
	zuorichulvzhishiliang int comment "昨日出铝指示量",
	jinrichulvzhishiliang int comment "今日出铝指示量",
	riqi datetime comment "日期",
	dianliuxiaolv float(10,8) comment "电流效率",
	class varchar(10) comment "类别"
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
